### ISSUE TITLE
没有medclip和knowledge attention的pkl文件

### ISSUE THREAD

**Issue by ZHENGER001** [zhangst431/TPRO#4]
2024-01-21 13:45:13,118 - evaluate_cls.py - INFO: Namespace(gpu=0, dataset='luad', cls_num_classes=4, model_path='path/to/classification/model', img_root='./data/LUAD-HistoSeg/train/img/*.png', palette_path='./datasets/luad_palette.npy', seed=0, backbone='mit_b1', split='train', label_feature_path=None, knowledge_feature_path=None, n_ratio=0.5, l1=0.3, l2=0.3, l3=0.4, save_dir='./work_dirs/luad/classification/predictions', seg_num_classes=5, cls_gate=0.15, mask_root='./data/LUAD-HistoSeg/train/mask/*.png')
2024-01-21 13:45:13,265 - evaluate_cls.py - INFO: using cuda:0 device.
Traceback (most recent call last):
  File "/home/tangfeilong/Desktop/ijcai/test/zhengzhou/TPRO-main/evaluate_cls.py", line 257, in <module>
    main()
  File "/home/tangfeilong/Desktop/ijcai/test/zhengzhou/TPRO-main/evaluate_cls.py", line 121, in main
    model = ClsNetwork(
            ^^^^^^^^^^^
  File "/home/tangfeilong/Desktop/ijcai/test/zhengzhou/TPRO-main/cls_network/model.py", line 72, in __init__
    with open("./text&features/text_features/{}.pkl".format(l_fea_path), "rb") as lf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './text&features/text_features/None.pkl'

**Comment by cqjtuhxf** [comment]
这是要自己手动设置参数的
